# Generated by Django 3.1.7 on 2021-04-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubtsBlog', '0002_auto_20210411_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answer_pics'),
        ),
    ]
