# Generated by Django 3.1.7 on 2021-04-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubtsBlog', '0003_auto_20210412_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doubt_pics'),
        ),
    ]
